name: Release new version

on:
  workflow_dispatch:
    inputs:
      list_pkg:
        description: "List nupkg on nuget.org (true/false)"
        required: true
        default: "false"

env:
  ANSI: "true"
  BUILD_CONFIG: Release
  NUGET_LIST_PKG: ${{ github.event.inputs.list_pkg }}

jobs:
  release:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4
      with:
        ref: ${{ github.head_ref }}
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v1.8.0
      with:
        dotnet-version: '5.0.x'

    - name: Publish Release
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
      run: ./build.sh publish -o ansi -- --clean
