name: Test incoming commits

on: [ push, pull_request ]

env:
  ANSI: "1"
  BUILD_CONFIG: Release

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2022]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2.4.0

    - name: Setup .NET
      uses: actions/setup-dotnet@v1.9.0
      with:
        dotnet-version: '6.0.x'

    - name: Test
      shell: bash
      run: ./build.sh test -o ansi
