name: Test incoming commits

on: [ push, pull_request ]

env:
  ANSI: "true"
  BUILD_CONFIG: Release

jobs:
  test:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4

    - name: Setup .NET
      uses: actions/setup-dotnet@v1.8.0
      with:
        dotnet-version: '5.0.x'

    - name: Quick test
      run: git remote -v

    # - name: Test
    #   run: ./build.sh test -o ansi
