name: Test incoming commits

on: [ push, pull_request ]

env:
  ANSI: "1"
  BUILD_CONFIG: Release

jobs:
  test:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2.4.0

    - name: Setup .NET
      uses: actions/setup-dotnet@v1.9.0
      with:
        dotnet-version: '6.0.x'

    - name: Test
      run: ./build.sh test -o ansi
